### ISSUE TITLE
Waiting for the essential requirement 1 of 5: "ssh"

### ISSUE THREAD

**Issue by mendezona** [abiosoft/colima#424]
### Description

I seem to be getting some sort of network error when trying to start Colima using the command `colima start --arch amd`.

I get the following error messages in terminal:

- [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
- did not receive an event with the "running" status
- FATA[0601] error starting vm: error at 'starting': exit status 1 

I receive more IPV6/IPV4 error related messages in serial.log but I'm not sure what to make of them. Any help would be appreciated! :)

[serial.log](https://github.com/abiosoft/colima/files/9548686/serial.log)

### Version

Colima Version: 0.4.4
Lima Version: 0.11.3
Qemu Version: 7.1.0

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. Open terminal
2. Type `colima start --arch amd`
3. Error message will appear after a few minutes

Attached is my serial.log

**Comment by mendezona** [comment]
Not sure if this thread is also related, seems to be different error output message - https://github.com/abiosoft/colima/issues/411

**Comment by abiosoft** [comment]
Can you try again with the development version `brew install --head colima` ?

**Comment by mendezona** [comment]
Hello, I believe I am still receiving a network error after installing the development version with the command above. Attached are the logs
[serial.log](https://github.com/abiosoft/colima/files/9593970/serial.log)

**Comment by abiosoft** [comment]
@mendezona how recent was your installation as I pushed some fixes shortly ago.

Also, can you kindly run with `colima start --very-verbose` and share the output here?

Thanks.

**Comment by mendezona** [comment]
@abiosoft - Hey I reinstalled the development version again 5 minutes ago and still getting the network error. Here is the serial.log after running colima start --arch amd, and then the serial and output logs after running colima start --very-verbose
[serial.log](https://github.com/abiosoft/colima/files/9594007/serial.log)
<img width="1074" alt="Screen Shot 2022-09-18 at 3 21 29 PM" src="https://user-images.githubusercontent.com/41711441/190904332-a6fd64d1-a18c-4a40-ba58-4a7a47244c89.png">
[serial.log](https://github.com/abiosoft/colima/files/9594047/serial.log)

**Comment by johntellsall** [comment]
This issue in Lima might be related: https://github.com/lima-vm/lima#stuck-on-waiting-for-the-essential-requirement-1-of-x-ssh

**Comment by gaspar09** [comment]
For others getting here, I had to

```
colima delete
colima start --arch x86_64
```

Colima downloaded the some x86_64 file and then proceeded. It still showed `Waiting for the essential requirement 1 of 5: "ssh"` twice for about a minute  but then finished.

**Comment by uyw4687** [comment]
You can specify profile name if colima delete doesn't work. 
colima delete {profile_name}
