### ISSUE TITLE
Panic on VM stop

### ISSUE THREAD

**Issue by x1unix** [abiosoft/colima#691]
### Description

I have a Colima instance that I've created with Apple Virtualization VM type (`-t vz`).

When I try to stop it using `colima stop`, process just hangs and I see a panic:

```
> [hostagent] panic: runtime/cgo: misuse of an invalid Handle
> [hostagent] goroutine 17 [running, locked to thread]:
> [hostagent] runtime/cgo.Handle.Value(...)
> [hostagent]   /opt/homebrew/Cellar/go/1.20.1/libexec/src/runtime/cgo/handle.go:124
> [hostagent] github.com/Code-Hex/vz/v3.changeStateOnObserver(0x0, 0x14000002680?)
> [hostagent]   /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/!code-!hex/vz/v3@v3.0.4/virtualization.go:
```

### Version

Colima Version: `0.5.4`
Lima Version: `0.15.0`
Qemu Version: 

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [x] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

`FATA[0000] colima is not running`

### Reproduction Steps

1. Create a new instance using `-t vz --vz-rosetta` 
2. Try to stop the VM using `colima stop`
3. Inspect output

**Comment by jsco2t** [comment]
Having the same issue on my M1 as well - repo environment appears to be similar. Thanks for reporting this!

**Comment by abiosoft** [comment]
It is same issue as this https://github.com/abiosoft/colima/issues/672, which is from upstream https://github.com/abiosoft/colima/issues/672#issuecomment-1486509695.

**Comment by abiosoft** [comment]
This has been fixed upstream at Lima.

**Comment by pmalek** [comment]
I am using `colima version HEAD-5f30c83` (current `main`) and I'm still seeing this 

```
{"level":"debug","msg":"guest agent event: {Time:2023-04-16 09:21:54.580366258 +0000 UTC LocalPortsAdded:[{IP:0.0.0.0 Port:5000} {IP:127.0.0.1 Port:55372} {IP::: Port:5000}] LocalPortsRemoved:[] Errors:[]}","time":"2023-04-16T11:21:55+02:00"}
{"level":"info","msg":"Forwarding TCP from 0.0.0.0:5000 to 0.0.0.0:5000","time":"2023-04-16T11:21:55+02:00"}
{"level":"info","msg":"Forwarding TCP from 127.0.0.1:55372 to 127.0.0.1:55372","time":"2023-04-16T11:21:55+02:00"}
{"level":"info","msg":"Forwarding TCP from [::]:5000 to 0.0.0.0:5000","time":"2023-04-16T11:21:55+02:00"}
{"error":"failed to run [ssh -F /dev/null -o IdentityFile=\"/Users/USER/.lima/_config/user\" -o IdentityFile=\"/Users/USER/.ssh/id_ed25519\"  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=lima -o ControlMaster=auto -o ControlPath=\"/Users/USER/.lima/colima/ssh.sock\" -o ControlPersist=5m -T -O forward -L 0.0.0.0:5000:[::]:5000 -N -f -p 60391 127.0.0.1 --]: \"\": exit status 255","level":"warning","msg":"failed to set up forwarding tcp port 5000 (negligible if already forwarded)","time":"2023-04-16T11:21:55+02:00"}
{"level":"debug","msg":"guest agent event: {Time:2023-04-16 09:22:21.579000855 +0000 UTC LocalPortsAdded:[] LocalPortsRemoved:[{IP::: Port:5000} {IP:0.0.0.0 Port:5000}] Errors:[]}","time":"2023-04-16T11:22:22+02:00"}
{"level":"info","msg":"Stopping forwarding TCP from [::]:5000 to 0.0.0.0:5000","time":"2023-04-16T11:22:22+02:00"}
{"level":"info","msg":"Stopping forwarding TCP from 0.0.0.0:5000 to 0.0.0.0:5000","time":"2023-04-16T11:22:22+02:00"}
{"level":"info","msg":"Received SIGINT, shutting down the host agent","time":"2023-04-16T11:22:32+02:00"}
{"level":"info","msg":"Shutting down the host agent","time":"2023-04-16T11:22:32+02:00"}
{"level":"debug","msg":"Stop forwarding unix sockets","time":"2023-04-16T11:22:32+02:00"}
{"level":"info","msg":"Stopping forwarding \"/var/run/docker.sock\" (guest) to \"/Users/USER/.colima/default/docker.sock\" (host)","time":"2023-04-16T11:22:32+02:00"}
{"level":"info","msg":"Stopping forwarding \"/var/run/docker.sock\" (guest) to \"/Users/USER/.colima/docker.sock\" (host)","time":"2023-04-16T11:22:32+02:00"}
{"level":"info","msg":"Stopping forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/USER/.lima/colima/ga.sock\" (host)","time":"2023-04-16T11:22:32+02:00"}
{"level":"debug","msg":"shutting down the SSH master","time":"2023-04-16T11:22:32+02:00"}
{"level":"debug","msg":"executing ssh for exiting the master: /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/USER/.lima/_config/user\" -o IdentityFile=\"/Users/USER/.ssh/id_ed25519\"  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=lima -o ControlMaster=auto -o ControlPath=\"/Users/USER/.lima/colima/ssh.sock\" -o ControlPersist=5m -O exit -p 60391 127.0.0.1]","time":"2023-04-16T11:22:32+02:00"}
{"level":"info","msg":"Shutting down VZ","time":"2023-04-16T11:22:33+02:00"}
{"level":"error","msg":"dhcp: unhandled message type: RELEASE","time":"2023-04-16T11:22:34+02:00"}
panic: runtime/cgo: misuse of an invalid Handle

goroutine 17 [running, locked to thread]:
runtime/cgo.Handle.Value(...)
	/opt/homebrew/Cellar/go/1.20.3/libexec/src/runtime/cgo/handle.go:124
github.com/Code-Hex/vz/v3.changeStateOnObserver(0x0, 0x14000002680?)
	/Users/USER/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/!code-!hex/vz/v3@v3.0.5/virtualization.go:160 +0xb0
```

**Comment by abiosoft** [comment]
@pmalek update Lima instead i.e. `brew upgrade lima`.

**Comment by pmalek** [comment]
```
limactl --version
limactl version HEAD-261b4cd
```

This is also using current `main`: https://github.com/lima-vm/lima/commit/261b4cdd315d2fbdfe49023eb7e1cb8ea87d625b.

```
brew info lima
==> lima: stable 0.15.1 (bottled), HEAD
Linux virtual machines
https://github.com/lima-vm/lima
/opt/homebrew/Cellar/lima/HEAD-261b4cd (74 files, 130.7MB) *
  Built from source on 2023-04-16 at 10:56:44
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lima.rb
```

**Comment by abiosoft** [comment]
@pmalek thanks for confirming, will inform upstream.
