### ISSUE TITLE
v0.6.2 breaks custom network setup

### ISSUE THREAD

**Issue by drallgood** [abiosoft/colima#879]
### Description

I had set up a bridged network so that I can have a custom bridged interface with a static IP (I need this so I can run a DNS server.. otherwise it would interfere with mDNS on the host system).

v0.6.2 broke this, because it overrides the network.yml file with a static one, so the "briged" network isn't defined anymore, which the override.yml references.

Result:
`errors inspecting instance: [field `networks[2].lima` references network "bridged" which is not defined in networks.yaml]`

### Version

colima version 0.6.2
git commit: 22d7e5fbc86d5b8e3b27065a762800bc7960a0ff
limactl version 0.18.0

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Reproduction Steps

1. create `.colima/_lima/_config/override.yaml` & define a new bridged network
2. start colima

**Comment by drallgood** [comment]
Additional information:

override.yml:
```
networks:
  - lima: bridged
 ```

Problem is that `.colima/_lima/_config/networks.yaml` now gets overridden with a default every time. So you can't specify anything custom in there

**Comment by abiosoft** [comment]
Are you customizing the `network.yaml` file solely for the purpose of using a bridged network?

**Comment by drallgood** [comment]
yes.

**Comment by rfields-equinix** [comment]
@drallgood Were you able to get this resolved? I have a similar problem.

**Comment by heijligers** [comment]
same here

**Comment by drallgood** [comment]
No I was not so far

**Comment by abiosoft** [comment]
Looks like I can finally get to this.

The main reason why a fixed IP address is not encourage is due to the fact that you can have multiple (profile) instances running and can cause undesired behaviour when there is a clash of IP address.

**Comment by abiosoft** [comment]
As a side note, the assigned IP address should be fixed and not change afterwards. Unless an extra profile is created.

**Comment by drallgood** [comment]
> Looks like I can finally get to this.
> 
> The main reason why a fixed IP address is not encourage is due to the fact that you can have multiple (profile) instances running and can cause undesired behaviour when there is a clash of IP address.

Good point. Doesn't solve the problem though. I need a fixed, externally assigned (or configurable) IP that cannot change later.
Anything else won't do it for a DNS server. UDP forwards won't work as port 53 is already taken on the host machine (and no other port is allowed for this so I can't even use a random port).
I've tried everything else and none of it worked. 

Until then I'm stuck on older versions of Colima.

**Comment by abiosoft** [comment]
@drallgood can you share your current `networks.yaml` file?

**Comment by drallgood** [comment]
@abiosoft Here's the networks.yml
It's mostly the default one from before v0.6.2

The static IP address assignment is handled by the DHCP server in my network

```
# Path to socket_vmnet executable. Because socket_vmnet is invoked via sudo it should be
# installed where only root can modify/replace it. This means also none of the
# parent directories should be writable by the user.
#
# The varRun directory also must not be writable by the user because it will
# include the socket_vmnet pid file. Those will be terminated via sudo, so replacing
# the pid file would allow killing of arbitrary privileged processes. varRun
# however MUST be writable by the daemon user.
#
# None of the paths segments may be symlinks, why it has to be /private/var
# instead of /var etc.
paths:
# socketVMNet requires Lima >= 0.12 .
# socketVMNet has precedence over vdeVMNet.
  socketVMNet: "/opt/homebrew/Cellar/socket_vmnet/1.1.4/bin/socket_vmnet"
# vdeSwitch and vdeVMNet are DEPRECATED.
#  vdeSwitch: /opt/vde/bin/vde_switch
#  vdeVMNet: /opt/vde/bin/vdey_vmnet
  varRun: /private/var/run/lima
  sudoers: /private/etc/sudoers.d/lima

group: everyone

networks:
  shared:
    mode: shared
    gateway: 192.168.105.1
    dhcpEnd: 192.168.105.254
    netmask: 255.255.255.0
  bridged:
    mode: bridged
    interface: en0
    # bridged mode doesn't have a gateway; dhcp is managed by outside network
  host:
    mode: host
    gateway: 192.168.106.1
    dhcpEnd: 192.168.106.254
    netmask: 255.255.255.0
  user-v2:
    mode: user-v2
    gateway: 192.168.5.2
    netmask: 255.255.255.0
```

**Comment by abiosoft** [comment]
The feature is being added https://github.com/abiosoft/colima/pull/1382.
